### ISSUE TITLE
Wrong naming of metastore tables on PostgreSQL

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/hive-old#1]
When using PostgreSQL as a backend, some metastore tables are not created with the right name, ending up with the following error:
```
org.datanucleus.store.rdbms.exceptions.MissingTableException: Required table missing : ""RUNTIME_STATS"" in Catalog "" Schema "". DataNucleus requires this table to perform its persistence operations. Either your MetaData is incorrect, or you need to enable "datanucleus.schema.autoCreateTables"
```
This is due to PostgreSQL forcing lowercase by default if the table name is not between quotes. The issue is tracked on Hive Jira here but the associated PR hasn't been merged: [HIVE-22101](https://issues.apache.org/jira/browse/HIVE-22101). It has been fixed in version 4.0 of the Hive metastore schema (see [hive-schema-4.0.0-alpha-1.postgres.sql](https://github.com/apache/hive/blob/master/standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0-alpha-1.postgres.sql)).

For example the table `RUNTIME_STATS` is created as follow:
https://github.com/TOSIT-IO/hive/blob/c3bc46fdcaf0a67d429190b66397d8faee5d1d33/standalone-metastore/src/main/sql/postgres/hive-schema-3.1.0.postgres.sql#L1841
PostgreSQL changes the table name to `runtime_stats` as the create statement does not use quote (should be `CREATE TABLE "RUNTIME_STATS" ...`)

**Comment by leopaul36** [comment]
I think we are looking for [HIVE-22546](https://issues.apache.org/jira/browse/HIVE-22546).

I tried to backport [9d61992d2f5e2a93af8de66d82085e7e126b4090](https://github.com/apache/hive/commit/9d61992d2f5e2a93af8de66d82085e7e126b4090) with some light conflicts.

It seems to be working:
```
...
 public | PART_PRIVS                    | table | hive
 public | REPL_TXN_MAP                  | table | hive
 public | ROLES                         | table | hive
 public | ROLE_MAP                      | table | hive
 public | RUNTIME_STATS                 | table | hive
 public | SCHEDULED_EXECUTIONS          | table | hive
 public | SCHEDULED_QUERIES             | table | hive
 public | SCHEMA_VERSION                | table | hive
 public | SDS                           | table | hive
...
```

I pushed the backport in the branch [branch-3.1-TDP-HIVE-22546](https://github.com/TOSIT-IO/hive/tree/branch-3.1-TDP-HIVE-22546)

**Note:** I have not tested Hive thoroughly with this fix

**Comment by Nuttymoon** [comment]
> I think we are looking for [HIVE-22546](https://issues.apache.org/jira/browse/HIVE-22546).
> 
> I tried to backport [9d61992d2f5e2a93af8de66d82085e7e126b4090](https://github.com/apache/hive/commit/9d61992d2f5e2a93af8de66d82085e7e126b4090) with some light conflicts.
> 
> It seems to be working:
> 
> ```
> ...
>  public | PART_PRIVS                    | table | hive
>  public | REPL_TXN_MAP                  | table | hive
>  public | ROLES                         | table | hive
>  public | ROLE_MAP                      | table | hive
>  public | RUNTIME_STATS                 | table | hive
>  public | SCHEDULED_EXECUTIONS          | table | hive
>  public | SCHEDULED_QUERIES             | table | hive
>  public | SCHEMA_VERSION                | table | hive
>  public | SDS                           | table | hive
> ...
> ```
> 
> I pushed the backport in the branch [branch-3.1-TDP-HIVE-22546](https://github.com/TOSIT-IO/hive/tree/branch-3.1-TDP-HIVE-22546)
> 
> **Note:** I have not tested Hive thoroughly with this fix

Nice! I think we can remove `upgrade-3.2.0-to-4.0.0.postgres.sql` as this does not make sense for our version. I will try to test the fix when I have the time.

**Comment by kpgtek** [comment]
> PostgreSQL changes the table name to `runtime_stats` as the create statement does not use quote (should be `CREATE TABLE "RUNTIME_STATS" ...`)

Note: if quotes are put in the object names, the application has also to use the quotes when querying the objects, otherwise, it  will fail with errors (I suppose this is already done in ```hive``` application).

**Comment by Nuttymoon** [comment]
> > PostgreSQL changes the table name to `runtime_stats` as the create statement does not use quote (should be `CREATE TABLE "RUNTIME_STATS" ...`)
> 
> Note: if quotes are put in the object names, the application has also to use the quotes when querying the objects, otherwise, it will fail with errors (I suppose this is already done in `hive` application).

Yes, the initial problem comes from the fact that Hive quotes all the table/column names when querying the RDBMS. We can see that 80% (57/74) of the tables are quoted in [hive-schema-3.1.0.postgres.sql](https://github.com/TOSIT-IO/hive/blob/branch-3.1-TDP/standalone-metastore/src/main/sql/postgres/hive-schema-3.1.0.postgres.sql). The PR just quotes the other 20% (=17 tables).
